name: Wildfly s2i Image CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'docs/**'
env:
  LANG: en_US.UTF-8
  S2I_URI: https://api.github.com/repos/openshift/source-to-image/releases/latest
  CEKIT_VERSION: 3.2.1
  QUAY_REPO: ${{ secrets.QUAY_REPO }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
jobs:
  wfci:
    name: Wildfly-s2i Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR ID
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber); 
      - name: Setup required system packages
        run: |
          echo PULL NUMBER: ${PULL_NUMBER}
          sudo apt-get update
          sudo apt-get install krb5-multidev
        if: env.QUAY_USERNAME != '' && env.QUAY_REPO != ''
      - name: Setup virtualenv and install cekit and required packages
        run: |
          sudo pip install virtualenv
          mkdir ~/cekit${{ env.CEKIT_VERSION }}
          virtualenv ~/cekit${{ env.CEKIT_VERSION }}
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          pip install cekit==${{ env.CEKIT_VERSION }} docker docker-squash odcs behave lxml
      - name: install s2i binary
        run: |
          echo ===== Installing s2i from ${{ env.S2I_URL }} =====
          mkdir /tmp/s2i/ && cd /tmp/s2i/
          curl -s ${{ env.S2I_URI }} \
           | grep browser_download_url \
           | grep linux-amd64 \
           | cut -d '"' -f 4 \
           | wget -qi -
           tar xvf source-to-image*.gz
           sudo mv s2i /usr/bin
           which s2i
           s2i version
      - name: Build 
        run: |
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          make
          docker image ls
      - name: Push to quay.io
        if: env.QUAY_USERNAME != '' && env.QUAY_REPO != ''
        run: |
            BUILDER_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:${PULL_NUMBER}"
            RUNTIME_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7:${PULL_NUMBER}"
            echo QUAY_REPO: "${{ secrets.QUAY_REPO }}"
            echo Pushing to quay.io with the tag :${PULL_NUMBER}
            echo BUILDER_IMAGE: ${BUILDER_IMAGE}
            echo RUNTIME_IMAGE: ${RUNTIME_IMAGE}
            docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io
            docker tag wildfly/wildfly-centos7:latest ${BUILDER_IMAGE}
            docker push ${BUILDER_IMAGE}
            docker tag wildfly/wildfly-runtime-centos7:latest ${RUNTIME_IMAGE}
            docker push ${RUNTIME_IMAGE}
      - name: Behave Tests
        run: |
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          pushd wildfly-builder-image
          cekit -v test behave --steps-url https://github.com/luck3y/behave-test-steps.git
          popd
      - name: Additional Tests
        run: |
          export IMAGE_VERSION=dev
          export NAMESPACE=wildfly
          export PLATFORM=centos7
          export IMAGE_NAME=${NAMESPACE}/wildfly-${PLATFORM}
          export RUNTIME_IMAGE_NAME=${NAMESPACE}/wildfly-runtime-${PLATFORM}
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          ./test/run
